name: link-check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Check links
        uses: peter-evans/link-checker@v1.2.2
        with:
          args: -v -r README.md
