name: link-check

on:
  push:
    paths:
      - '**/README.md'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Check links
        uses: lycheeverse/lychee-action@v1.0.9
        with:
          args: --verbose --no-progress **/README.md
